### ISSUE TITLE
[ui] [safari] --color-high/low calc not working

### ISSUE THREAD

**Issue by r2d4** [openauthjs/openauth#27]
<img width="528" alt="image" src="https://github.com/user-attachments/assets/272348d6-847c-4422-8bd2-b8a5634ad32f">

Not sure what's exactly unsupported in safari -- manual fix is to just add a fallback in theme.css. 

```css
:root {
     @media (prefers-color-scheme: light) {
        --color-high: #000;
    }
    @media (prefers-color-scheme: dark) {
        --color-high: #fff;
    }
}
```
